replicaCount: 3

image:
  repository: ghcr.io/suryamjv/devops-practice
  tag: "f8c1df9c0a4fc9dd4aa5e12ba3a73e63369db42b"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    memory: 256Mi

postgres:
  enabled: true
  image: postgres:16-alpine
  storage: 1Gi

db:
  name: visitsdb
  user: appuser
  password: changeme