replicaCount: 3

image:
  repository: ghcr.io/suryamjv/devops-practice
  tag: "fe29b88c2898a5390637cf06d172962e571e8ef7"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    memory: 256Mi

postgres:
  enabled: true
  image: postgres:16-alpine
  storage: 1Gi

db:
  name: visitsdb
  user: appuser
  password: changeme