replicaCount: 3

image:
  repository: ghcr.io/suryamjv/devops-practice
  tag: "6e5ae2a3bea1d346848eca1a24328db5d6433f4b"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    memory: 256Mi

postgres:
  enabled: true
  image: postgres:16-alpine
  storage: 1Gi

db:
  name: visitsdb
  user: appuser
  password: changeme