apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: visits
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/suryamjv/devops-practice.git
    targetRevision: main
    path: chart
  destination:
    server: https://kubernetes.default.svc
    namespace: visits
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
