apiVersion: v1
kind: Secret
metadata:
  name: {{ include "visits.fullname" . }}-db
  labels:
    {{- include "visits.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.db.name | quote }}
  POSTGRES_USER: {{ .Values.db.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.db.password | quote }}