apiVersion: v1
kind: Service
metadata:
  name: {{ include "visits.fullname" . }}-web
  labels:
    {{- include "visits.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: web
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}